//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.81.0.
// 
namespace VireoxConfigurator
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class root
    {

        private groupType progettoField;

        private groupType nodoField;

        private groupType variabileField;

        private groupType usersField;

        private groupType[] comunicazioniField;

        private groupType[] protocolliField;

        /// <remarks/>
        public groupType Progetto
        {
            get
            {
                return this.progettoField;
            }
            set
            {
                this.progettoField = value;
            }
        }

        /// <remarks/>
        public groupType Nodo
        {
            get
            {
                return this.nodoField;
            }
            set
            {
                this.nodoField = value;
            }
        }

        /// <remarks/>
        public groupType Variabile
        {
            get
            {
                return this.variabileField;
            }
            set
            {
                this.variabileField = value;
            }
        }

        /// <remarks/>
        public groupType Users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("gruppo", IsNullable = false)]
        public groupType[] Comunicazioni
        {
            get
            {
                return this.comunicazioniField;
            }
            set
            {
                this.comunicazioniField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("gruppo", IsNullable = false)]
        public groupType[] Protocolli
        {
            get
            {
                return this.protocolliField;
            }
            set
            {
                this.protocolliField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class groupType
    {

        private proprietaType[] proprietaField;

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("proprieta")]
        public proprietaType[] proprieta
        {
            get
            {
                return this.proprietaField;
            }
            set
            {
                this.proprietaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class proprietaType
    {

        private string nomeVisualizzatoField;

        private string gruppoVisualizzazioneField;

        private string nomeSalvatoField;

        private string nomeEsportazioneGPMField;

        private string defaultValueField;

        private bool visibileField;

        private bool visibileFieldSpecified;

        private bool tipoDefinitoField;

        private decimal ordineField;

        private bool ordineFieldSpecified;

        private string helpField;

        private string[] parametroField;

        private string nameField;

        public override string ToString()
        {
            return nameField;
        }
        /// <remarks/>
        public string NomeVisualizzato
        {
            get
            {
                return this.nomeVisualizzatoField;
            }
            set
            {
                this.nomeVisualizzatoField = value;
            }
        }

        /// <remarks/>
        public string GruppoVisualizzazione
        {
            get
            {
                return this.gruppoVisualizzazioneField;
            }
            set
            {
                this.gruppoVisualizzazioneField = value;
            }
        }

        /// <remarks/>
        public string NomeSalvato
        {
            get
            {
                return this.nomeSalvatoField;
            }
            set
            {
                this.nomeSalvatoField = value;
            }
        }

        /// <remarks/>
        public string NomeEsportazioneGPM
        {
            get
            {
                return this.nomeEsportazioneGPMField;
            }
            set
            {
                this.nomeEsportazioneGPMField = value;
            }
        }

        /// <remarks/>
        public string DefaultValue
        {
            get
            {
                return this.defaultValueField;
            }
            set
            {
                this.defaultValueField = value;
            }
        }

        /// <remarks/>
        public bool Visibile
        {
            get
            {
                return this.visibileField;
            }
            set
            {
                this.visibileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VisibileSpecified
        {
            get
            {
                return this.visibileFieldSpecified;
            }
            set
            {
                this.visibileFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool TipoDefinito
        {
            get
            {
                return this.tipoDefinitoField;
            }
            set
            {
                this.tipoDefinitoField = value;
            }
        }

        /// <remarks/>
        public decimal Ordine
        {
            get
            {
                return this.ordineField;
            }
            set
            {
                this.ordineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrdineSpecified
        {
            get
            {
                return this.ordineFieldSpecified;
            }
            set
            {
                this.ordineFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Help
        {
            get
            {
                return this.helpField;
            }
            set
            {
                this.helpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parametro")]
        public string[] parametro
        {
            get
            {
                return this.parametroField;
            }
            set
            {
                this.parametroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public string parametri
        {
            get
            {
                string ret = "";
                for (int i = 0;i < parametroField.Length;i++) {
                    ret += parametroField[i];
                    if (i != parametroField.Length - 1)
                        ret += "┼";
                }
                return ret;
            }
            set
            {
                parametroField = value.Split('┼');
            }
        }
    }
}